[tool.poetry]
name = "battle-snake-python"
version = "1.2.0"
description = "a hungry hungry snake"
authors = ["Battlesnake Developers <developers@battlesnake.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cherrypy = "^18.6"
